insert into items (id, name, category, description) values (1000, 'Nike', 'shoes', 'Just Do It.');
insert into items (id, name, category, description) values (1001, 'Reebok', 'shoes', 'Run Fast. Go Far.');
insert into items (id, name, category, description) values (1002, 'Adidas', 'shoes', 'All Day I Dream About Sports');
insert into items (id, name, category, description) values (1003, 'New Balance', 'shoes', 'Run like you mean it.');
insert into items (id, name, category, description) values (1004, 'Clarks', 'shoes', 'Always be walking in amazing comfort.');
insert into items (id, name, category, description) values (1005, 'Puma', 'shoes', 'Meow. This cat wins by stealth.');
insert into items (id, name, category, description) values (1006, 'Sketchers', 'shoes', 'Tragically hip, very nice, everyone likes.');
insert into items (id, name, category, description) values (1007, 'Uggs', 'shoes', 'Dead animal, inside out.');
insert into items (id, name, category, description) values (1008, 'Dockers', 'pants', 'Pants that should look more expensive than they are, but don''t.');
insert into items (id, name, category, description) values (1009, 'Levis', 'pants', 'Ruff. Tuff. Bloo. Everyone wants one.');
insert into items (id, name, category, description) values (1010, 'Wrangler', 'pants', 'I could be Levis, but I think I will be ok like this too.');
insert into items (id, name, category, description) values (1011, 'Gap', 'pants', 'So smart you will wear many.');
insert into items (id, name, category, description) values (1012, 'Khakis', 'pants', 'Look like you know what you are doing.');
insert into items (id, name, category, description) values (1013, 'Chinos', 'pants', 'Also look like you know what you''re doing, mostly.');
insert into items (id, name, category, description) values (1014, 'Woosters', 'pants', 'Look awesome in these things, they have wings and flaps.');
insert into items (id, name, category, description) values (1015, 'Gorgons', 'pants', 'You will marry your lover.');
insert into items (id, name, category, description) values (1016, 'Scoobys', 'pants', 'Don''t be scared to take the leap with these on.');
insert into items (id, name, category, description) values (1017, 'Arbo', 'shirt', 'This will come untucked a lot, because good.');
insert into items (id, name, category, description) values (1018, 'Perdan', 'shirt', 'Its not a very good name, but it sells a lot.');
insert into items (id, name, category, description) values (1019, 'Hertzog', 'shirt', 'Some crazy dude made this shirt. We are still selling them.');
insert into items (id, name, category, description) values (1020, 'Braunfalter', 'shirt', 'You can make your own happiness with thing on.');
insert into items (id, name, category, description) values (1021, 'Drebens', 'shirt', 'The greatest risk is not taking one.');
insert into items (id, name, category, description) values (1022, 'Jesters', 'shirt', 'All the fun you can have with clothes on.');
insert into items (id, name, category, description) values (1023, 'Blue Rips', 'shirt', 'Very blue, very nice, wear everywhere.');
insert into items (id, name, category, description) values (1024, 'Vertal', 'shirt', 'Big, tall, and everything else also.');
insert into items (id, name, category, description) values (1025, 'Pulman', 'shirt', 'A great shirt, built to take the travel you can give it.');
insert into items (id, name, category, description) values (1026, 'Shirtly', 'shirt', 'Try one and it will keep showing up in the mail.');
insert into items (id, name, category, description) values (1027, 'Burberry', 'knits', 'Very wrap, but you will have an empty pocket.');
insert into items (id, name, category, description) values (1028, 'Mulberry', 'knits', 'Wealth awaits you very soon.');
insert into items (id, name, category, description) values (1029, 'Jumberry', 'knits', 'If you feel you are right, stand firmly by your convictions.');
insert into items (id, name, category, description) values (1030, 'Gumberry', 'knits', 'If winter comes, can spring be far behind?');
insert into items (id, name, category, description) values (1031, 'Plaidonic', 'knits', 'Keep your eye out for someone special.');
insert into items (id, name, category, description) values (1032, 'Weavers', 'knits', 'You are very talented in many ways.');
insert into items (id, name, category, description) values (1033, 'Loomster', 'knits', 'A stranger, is a friend you have not spoken to yet.');
insert into items (id, name, category, description) values (1034, 'Yarnery', 'knits', 'A new voyage will fill your life with untold memories.');
insert into items (id, name, category, description) values (1035, 'Microtech', 'knits', 'You will travel to many exotic places in your lifetime.');
insert into items (id, name, category, description) values (1036, 'Stitchers', 'knits', 'Your ability for accomplishment will follow with success.');
insert into items (id, name, category, description) values (1037, 'Trunks', 'beach', 'Nothing astonishes men so much as common sense and plain dealing.');
insert into items (id, name, category, description) values (1038, 'Divers', 'beach', 'Its amazing how much good you can do if you dont care who gets the credit.');
insert into items (id, name, category, description) values (1039, 'BigReds', 'beach', 'Everyone agrees. You are the best.');
insert into items (id, name, category, description) values (1040, 'SunSand', 'beach', 'LIFE CONSIST NOT IN HOLDING GOOD CARDS, BUT IN PLAYING THOSE YOU HOLD WELL.');
insert into items (id, name, category, description) values (1041, 'SurfLogic', 'beach', 'Jealousy doesn''t open doors, it closes them!');
insert into items (id, name, category, description) values (1042, 'Sandcastle', 'beach', 'It''s better to be alone sometimes.');
insert into items (id, name, category, description) values (1043, 'Coral', 'beach', 'When fear hurts you, conquer it and defeat it!');
insert into items (id, name, category, description) values (1044, 'Palman', 'beach', 'Let the deeds speak.');
insert into items (id, name, category, description) values (1045, 'Harvard', 'sport', 'The original preppy look.');
insert into items (id, name, category, description) values (1046, 'Yale', 'sport', 'Preppy, and without apology.');
insert into items (id, name, category, description) values (1047, 'Columbia', 'sport', 'Modern, urban, sleek, classy without being stuffy.');
insert into items (id, name, category, description) values (1048, 'Penn', 'sport', 'Easygoing, fun, good for all occasions.');
insert into items (id, name, category, description) values (1049, 'Princeton', 'sport', 'You either have it or you don''t.');
