server:
  port: 8081

#eureka:
#  client:
#    registryFetchIntervalSeconds: 5

ribbon:
  IsSecure: false

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

---

spring:
  profiles: pact

ribbon:
  eureka:
    enabled: false

hystrix:
  command:
    randomFortune:
      execution.isolation.thread.timeoutInMilliseconds: 2000

item:
  ribbon:
    listOfServers: localhost:8080
    
price:
  ribbon:
    listOfServers:  localhost:8090
